### ISSUE TITLE
Docker missing mosdepth dependency

### ISSUE THREAD

**Issue by VojtechBarton** [bendda/mitopy#1]
Run with docker exited with:
2024-01-25 09:58:59,470 [ERROR] - Executable mosdepth not found.

[mitopy_log.txt](https://github.com/bendda/mitopy/files/14049358/mitopy_log.txt)

Mosdepth executable is missing in docker.

**Comment by bendda** [comment]
There was a permission issue when running with Singularity. It should be fixed in the updated Docker image.
